<?php
//drupal_add_js(drupal_get_path('module', 'block_get_admin') . '/js/get_admin.js');
//public  $user_info = user_load($user->uid);
/**
 * Implement hook_menu
 */
//function block_get_admin_menu(){
//        $items['examples/get_admin'] = array(
//        'page callback' => 'drupal_get_form',
//        'page arguments' => array('block_get_admin_form'),
//        'access callback' => TRUE,
//        'title' => 'Block get info of admin'
//    );
//    return $items;
//}
//
//function block_get_admin_form($form, &$form_state){
//    $form['get_admin'] = array(
//        '#type' => 'textfield',
//        '#title' => t('Input content')
//    );
//
//    $form['submit'] = array(
//        '#type' => 'submit', 
//        '#value' => t('Submit'));
//    
//    return $form;
//    
//}
//
//function block_get_admin_form_submit($form, &$form_state) {
//    
//}

//function block_get_admin_form_alter(&$form, &$form_state, $form_id) {
//    
//    echo "<prev>";
//    print_r($form['type']['#value']);
//    echo "</prev>";
//    die();
//}

function block_get_admin_menu() {
  $items = array();
  $items['examples/get_admin'] = array(
    'title' => t('My form'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('block_get_admin_form'),
    'access arguments' => array('access content'),
    'description' => t('My form'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implement hook js
 */
//function block_get_admin_js_alter(&$javascript){
//    $javascript['js/get_admin.js']['data'] = drupal_get_path('module', 'Js test');
//}

/**
 * Returns the render array for the form.
 */
function block_get_admin_form($form, &$form_state) {
  $form['name'] = array(
    '#type' => 'fieldset',
    '#title' => t('Name'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );
  $form['name']['first'] = array(
    '#type' => 'textfield',
    '#title' => t('First name'),
    '#required' => TRUE,
    '#default_value' => "First name",
    '#description' => "Please enter your first name.",
    '#size' => 20,
    '#maxlength' => 20,
  );
  $form['name']['last'] = array(
    '#type' => 'textfield',
    '#title' => t('Last name'),
    '#required' => TRUE,
  );
  $form['name']['mail'] = array(
      '#type' => 'textfield',
      '#title' => t('Email'),
      '#required' => TRUE,
      '#attributes' => array(
          'onclick' => 'clickclear(this,"Email")'
      ),
      '#value' => t('Email'),
  );
  $form['year_of_birth'] = array(
    '#type' => 'textfield',
    '#title' => "Year of birth",
    '#description' => 'Format is "YYYY"',
  );  
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit',
  );
  return $form;
}

/**
 * Validates the form.
 */
function block_get_admin_form_validate($form, &$form_state) {

    // valid year
    $year_of_birth = $form_state['values']['year_of_birth'];
    if ($year_of_birth && ($year_of_birth < 1900 || $year_of_birth > 2000)) {
        form_set_error('year_of_birth', 'Enter a year between 1900 and 2000.');
    }
    
    //valid email
    $mail = $form_state['values']['mail'];
    if(filter_var($mail, FILTER_VALIDATE_EMAIL) == FALSE) {
        form_set_error('mail','Email format error');
    }
}

/**
 * Add a submit handler/function to the form.
 *
 * This will add a completion message to the screen when the
 * form successfully processes
 */
function block_get_admin_form_submit($form, &$form_state) {
    
//    $validUser = user_load_by_name($form_state['values']['last']);
//    $user_info = array(
//        'name' => $form_state['values']['last'],
//        'mail' => $form_state['values']['mail'],    
//    );
//    
//    if(!empty($user_info) && !$validUser){
//        user_save(null, $user_info);
//    }
//     
//    
//    drupal_set_message(t('Hello ').$form_state['values']['first'].'!');
    
    $first_name = $form_state['values']['first']; 
    $last_name = $form_state['values']['last'];

    drupal_goto("/admin/modules");
}

//

function block_show_info_admin() {
    $page = array(
        '#type' => 'markup',
        '#markup' => t('Get infomation of admin'),
    );
    
    return $page;
}

function block_get_admin_block_info() {
    $blocks['block_get_info_admin'] = array(
        'info' => t('Example: get information of admin'),
        'cache' => DRUPAL_CACHE_PER_ROLE,
        'status' => TRUE,
        'region' => 'sidebar_first',
    );
    
    return $blocks;
}

function block_get_admin_block_view($delta) {
    if ($delta = 'block_get_info_admin') {
        $block['subject'] = t('Show information of admin');
        $block['content'] = block_get_admin_content($delta);
    }
    
    return $block;
}

function block_get_admin_content($name_block){
    global $user;
    if($name_block = 'block_get_info_admin'){
         $result = 'Hello '.$user->name .'<br>' . 'Email: '.$user->mail;
    }
    
    return $result;
}

